# render.yaml
# Versión FINAL con un Job para inicializar la base de datos

services:
  # 1. Un "Job" para inicializar la BD. Se ejecuta una sola vez.
  - type: job
    name: db-setup
    plan: free # Los jobs son gratis si se ejecutan en menos de 5 mins
    # Este comando importa tu función y la ejecuta
    startCommand: "python -c 'from database import init_db; init_db()'"

  # 2. Tu servicio web. SOLO se iniciará después de que el Job termine.
  - type: web
    name: finance-tracker
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taraska
          property: connectionString
    # Esta línea es NUEVA e importante.
    # Le dice a la app que espere a que el Job de la BD termine.
    initialDeployHook: "python -c 'from database import init_db; init_db()'"


databases:
  # 3. Tu base de datos.
  - name: taraska
    plan: free