# render.yaml
# Versión final, simple y correcta.

databases:
  # Define tu base de datos primero
  - name: taraska
    plan: free

services:
  # Define tu aplicación web
  - type: web
    name: finance-tracker
    env: python
    plan: free
    # 1. Instala las dependencias
    buildCommand: "pip install -r requirements.txt"
    # 2. Inicia la app con Gunicorn
    startCommand: "gunicorn app:app"
    # 3. Este hook se ejecuta UNA SOLA VEZ, solo en el primer deploy.
    #    Aquí es donde creamos las tablas de la base de datos.
    initialDeployHook: "python -c 'from database import init_db; init_db()'"
    envVars:
      # 4. Conecta la app a la base de datos de forma automática
      - key: DATABASE_URL
        fromDatabase:
          name: taraska
          property: connectionString