# render.yaml
# Versi贸n corregida y lista para producci贸n

services:
  # Tu servicio web (la aplicaci贸n Python)
  - type: web
    name: finance-tracker
    env: python
    plan: free
    # CORRECTO: Instala las dependencias de tu proyecto
    buildCommand: "pip install -r requirements.txt"
    # CORRECTO: Inicia la app con un servidor de producci贸n
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          # Este nombre debe coincidir con el nombre del servicio de la base de datos de abajo
          name: taraska
          property: connectionString

# Tu servicio de base de datos
databases:
  - name: taraska
    plan: free